version: 0.2

phases:
  install:
    commands:
      - make install
  build:
    commands:
      - make bare_build
  post_build:
    commands:
      - make bare_extract
# artifacts:
#   files:
#     - dist/index.js
#   discard-paths: yes
